# Generated by Django 3.0.11 on 2021-01-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('origins', models.CharField(max_length=30)),
                ('word_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
