# Generated by Django 3.0.11 on 2021-01-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20210125_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=30), max_length=100),
        ),
    ]
