# Generated by Django 3.0.11 on 2021-01-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_word_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='definition',
            field=models.CharField(default='a common greeting between people', max_length=100),
            preserve_default=False,
        ),
    ]
