# Generated by Django 3.0.11 on 2021-01-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_remove_word_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='context',
            field=models.TextField(default='boop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='definition',
            field=models.TextField(default='boop'),
            preserve_default=False,
        ),
    ]
