# Generated by Django 3.0.11 on 2021-01-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_auto_20210126_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='word',
            name='slug',
            field=models.SlugField(),
        ),
    ]
