# Generated by Django 3.0.11 on 2021-01-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_auto_20210127_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
