# Generated by Django 3.0.11 on 2021-01-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_auto_20210128_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_type',
            field=models.CharField(choices=[('academic', 'academic'), ('common', 'common'), ('slang', 'slang')], default='common', max_length=10),
        ),
    ]
